server:
  port: ${PORT:8083}
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    context-path: /api/cinema

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        data:
          rest: debug

spring:
  application:
    name: cinema-service

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}

  jackson:
    time-zone: "America/Guatemala"
    mapper:
      "[ACCEPT_CASE_INSENSITIVE_ENUMS]": true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  rsa:
    public-key: classpath:certs/public-key.pem

client:
  services:
    auth-identity: ${AUTH-IDENTITY_URL:http://localhost:8081}
    movie: ${MOVIE_URL:http://localhost:8084}

#Configuración para rabir
rabbitmq:
  host: ${RABBIT_HOST:localhost}
  port: ${RABBIT_PORT:5672}
  username: ${RABBIT_USER:guest}
  password: ${RABBIT_PASS:guest}

  # Detalles del Exchange y las Routing Keys
  # Eventos usados por usuario
  exchange:
    showTime: showTime.exchange
    wallet: wallet.exchange

  routing:
    showTime_created: showTime.created
    wallet_created: wallet.created
